#!/usr/bin/env python3
"""Regenerate web/dashboard_data.js from the project's computed aggregates.

Reads dashboard/real_kpis.json (produced by the Bronze -> Silver -> Gold
pipeline) and writes a browser-friendly JS file with `const dashboard_data`
so web/index.html renders fully offline with no fetch/CORS issues.

Usage:
    python web/generate_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
SRC = ROOT / "dashboard" / "real_kpis.json"
OUT = WEB / "dashboard_data.js"


def read_json(path: Path):
    """Read a JSON file regardless of whether it is UTF-8 or UTF-16."""
    for encoding in ("utf-8-sig", "utf-16", "utf-16-le"):
        try:
            return json.loads(path.read_text(encoding=encoding))
        except (UnicodeDecodeError, json.JSONDecodeError):
            continue
    raise SystemExit(f"Could not decode {path} as UTF-8 or UTF-16")


def main() -> None:
    if not SRC.exists():
        raise SystemExit(f"Source not found: {SRC}")

    data = read_json(SRC)
    js = (
        "// Auto-generated by web/generate_data.py - do not edit by hand.\n"
        "// Source: dashboard/real_kpis.json (Bronze -> Silver -> Gold pipeline)\n"
        "const dashboard_data = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(js):,} bytes)")


if __name__ == "__main__":
    main()